package com.anypresence.anypresence_inc.citi_mobile_challenge.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsRevenue;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CAPITALMARKETSREVENUES.
 */
public class CapitalMarketsRevenueDao
		extends
			AbstractDao<CapitalMarketsRevenue, Long> {

	public static final String TABLENAME = "CAPITALMARKETSREVENUES";

	/**
	 * Properties of entity CapitalMarketsRevenue.<br/>
	 * Can be used for QueryBuilder and for referencing column names.
	 */
	public static class Properties {
		public final static Property Id = new Property(0, Long.class, "id",
				true, "_id");
		public final static Property ClientId = new Property(1, String.class,
				"clientId", false, "CLIENT_ID");
		public final static Property ClientName = new Property(2, String.class,
				"clientName", false, "CLIENT_NAME");
		public final static Property ClientTier = new Property(3, String.class,
				"clientTier", false, "CLIENT_TIER");
		public final static Property GrossComm = new Property(4, Float.class,
				"grossComm", false, "GROSS_COMM");
		public final static Property Month = new Property(5, String.class,
				"month", false, "MONTH");
		public final static Property ProductId = new Property(6, String.class,
				"productId", false, "PRODUCT_ID");
		public final static Property ProductName = new Property(7,
				String.class, "productName", false, "PRODUCT_NAME");
		public final static Property ProfitLoss = new Property(8, Float.class,
				"profitLoss", false, "PROFIT_LOSS");
		public final static Property Region = new Property(9, String.class,
				"region", false, "REGION");
		public final static Property Year = new Property(10, Integer.class,
				"year", false, "YEAR");
		public final static Property Scope = new Property(11, String.class,
				"scope", false, "SCOPE");
		public final static Property ObjectId = new Property(12, String.class,
				"objectId", false, "OBJECT_ID");
		public final static Property _cacheUpdatedAt = new Property(13,
				java.util.Date.class, "_cacheUpdatedAt", false,
				"_CACHE_UPDATED_AT");
		public final static Property ApCachedRequestId = new Property(14,
				Long.class, "apCachedRequestId", false, "AP_CACHED_REQUEST_ID");
	};

	private DaoSession daoSession;

	public CapitalMarketsRevenueDao(DaoConfig config) {
		super(config);
	}

	public CapitalMarketsRevenueDao(DaoConfig config, DaoSession daoSession) {
		super(config, daoSession);
		this.daoSession = daoSession;
	}

	/** Creates the underlying database table. */
	public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "'CAPITALMARKETSREVENUES' (" + //
				"'_id' INTEGER PRIMARY KEY ," + // 0: id
				"'CLIENT_ID' TEXT," + // 1: clientId
				"'CLIENT_NAME' TEXT," + // 2: clientName
				"'CLIENT_TIER' TEXT," + // 3: clientTier
				"'GROSS_COMM' REAL," + // 4: grossComm
				"'MONTH' TEXT," + // 5: month
				"'PRODUCT_ID' TEXT," + // 6: productId
				"'PRODUCT_NAME' TEXT," + // 7: productName
				"'PROFIT_LOSS' REAL," + // 8: profitLoss
				"'REGION' TEXT," + // 9: region
				"'YEAR' INTEGER," + // 10: year
				"'SCOPE' TEXT," + // 11: scope
				"'OBJECT_ID' TEXT," + // 12: objectId
				"'_CACHE_UPDATED_AT' INTEGER," + // 13: _cacheUpdatedAt
				"'AP_CACHED_REQUEST_ID' INTEGER);"); // 14: apCachedRequestId
		// Add Indexes
		db.execSQL("CREATE UNIQUE INDEX "
				+ constraint
				+ "IDX_CAPITALMARKETSREVENUES_OBJECT_ID ON CAPITALMARKETSREVENUES"
				+ " (OBJECT_ID);");
	}

	/** Drops the underlying database table. */
	public static void dropTable(SQLiteDatabase db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "")
				+ "'CAPITALMARKETSREVENUES'";
		db.execSQL(sql);
	}

	/** @inheritdoc */
	@Override
	protected void bindValues(SQLiteStatement stmt, CapitalMarketsRevenue entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		String clientId = entity.getClientId();
		if (clientId != null) {
			stmt.bindString(2, clientId);
		}

		String clientName = entity.getClientName();
		if (clientName != null) {
			stmt.bindString(3, clientName);
		}

		String clientTier = entity.getClientTier();
		if (clientTier != null) {
			stmt.bindString(4, clientTier);
		}

		Float grossComm = entity.getGrossComm();
		if (grossComm != null) {
			stmt.bindDouble(5, grossComm);
		}

		String month = entity.getMonth();
		if (month != null) {
			stmt.bindString(6, month);
		}

		String productId = entity.getProductId();
		if (productId != null) {
			stmt.bindString(7, productId);
		}

		String productName = entity.getProductName();
		if (productName != null) {
			stmt.bindString(8, productName);
		}

		Float profitLoss = entity.getProfitLoss();
		if (profitLoss != null) {
			stmt.bindDouble(9, profitLoss);
		}

		String region = entity.getRegion();
		if (region != null) {
			stmt.bindString(10, region);
		}

		Integer year = entity.getYear();
		if (year != null) {
			stmt.bindLong(11, year);
		}

		String scope = entity.getScope();
		if (scope != null) {
			stmt.bindString(12, scope);
		}

		String objectId = entity.getObjectId();
		if (objectId != null) {
			stmt.bindString(13, objectId);
		}

		java.util.Date _cacheUpdatedAt = entity.get_cacheUpdatedAt();
		if (_cacheUpdatedAt != null) {
			stmt.bindLong(14, _cacheUpdatedAt.getTime());
		}

		Long apCachedRequestId = entity.getApCachedRequestId();
		if (apCachedRequestId != null) {
			stmt.bindLong(15, apCachedRequestId);
		}
	}

	@Override
	protected void attachEntity(CapitalMarketsRevenue entity) {
		super.attachEntity(entity);
		entity.__setDaoSession(daoSession);
	}

	/** @inheritdoc */
	@Override
	public Long readKey(Cursor cursor, int offset) {
		return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
	}

	/** @inheritdoc */
	@Override
	public CapitalMarketsRevenue readEntity(Cursor cursor, int offset) {
		CapitalMarketsRevenue entity = new CapitalMarketsRevenue(
				//
				cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
				cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // clientId
				cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // clientName
				cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // clientTier
				cursor.isNull(offset + 4) ? null : cursor.getFloat(offset + 4), // grossComm
				cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // month
				cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // productId
				cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // productName
				cursor.isNull(offset + 8) ? null : cursor.getFloat(offset + 8), // profitLoss
				cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // region
				cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // year
				cursor.isNull(offset + 11) ? null : cursor
						.getString(offset + 11), // scope
				cursor.isNull(offset + 12) ? null : cursor
						.getString(offset + 12), // objectId
				cursor.isNull(offset + 13) ? null : new java.util.Date(cursor
						.getLong(offset + 13)), // _cacheUpdatedAt
				cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14) // apCachedRequestId
		);
		return entity;
	}

	/** @inheritdoc */
	@Override
	public void readEntity(Cursor cursor, CapitalMarketsRevenue entity,
			int offset) {
		entity.setId(cursor.isNull(offset + 0) ? null : cursor
				.getLong(offset + 0));
		entity.setClientId(cursor.isNull(offset + 1) ? null : cursor
				.getString(offset + 1));
		entity.setClientName(cursor.isNull(offset + 2) ? null : cursor
				.getString(offset + 2));
		entity.setClientTier(cursor.isNull(offset + 3) ? null : cursor
				.getString(offset + 3));
		entity.setGrossComm(cursor.isNull(offset + 4) ? null : cursor
				.getFloat(offset + 4));
		entity.setMonth(cursor.isNull(offset + 5) ? null : cursor
				.getString(offset + 5));
		entity.setProductId(cursor.isNull(offset + 6) ? null : cursor
				.getString(offset + 6));
		entity.setProductName(cursor.isNull(offset + 7) ? null : cursor
				.getString(offset + 7));
		entity.setProfitLoss(cursor.isNull(offset + 8) ? null : cursor
				.getFloat(offset + 8));
		entity.setRegion(cursor.isNull(offset + 9) ? null : cursor
				.getString(offset + 9));
		entity.setYear(cursor.isNull(offset + 10) ? null : cursor
				.getInt(offset + 10));
		entity.setScope(cursor.isNull(offset + 11) ? null : cursor
				.getString(offset + 11));
		entity.setObjectId(cursor.isNull(offset + 12) ? null : cursor
				.getString(offset + 12));
		entity.set_cacheUpdatedAt(cursor.isNull(offset + 13)
				? null
				: new java.util.Date(cursor.getLong(offset + 13)));
		entity.setApCachedRequestId(cursor.isNull(offset + 14) ? null : cursor
				.getLong(offset + 14));
	}

	/** @inheritdoc */
	@Override
	protected Long updateKeyAfterInsert(CapitalMarketsRevenue entity, long rowId) {
		entity.setId(rowId);
		return rowId;
	}

	/** @inheritdoc */
	@Override
	public Long getKey(CapitalMarketsRevenue entity) {
		if (entity != null) {
			return entity.getId();
		} else {
			return null;
		}
	}

	/** @inheritdoc */
	@Override
	protected boolean isEntityUpdateable() {
		return true;
	}

	private String selectDeep;

	protected String getSelectDeep() {
		if (selectDeep == null) {
			StringBuilder builder = new StringBuilder("SELECT ");
			SqlUtils.appendColumns(builder, "T", getAllColumns());
			builder.append(',');
			SqlUtils.appendColumns(builder, "T0", daoSession
					.getAPCachedRequestDao().getAllColumns());
			builder.append(" FROM CAPITALMARKETSREVENUES T");
			builder.append(" LEFT JOIN APCACHED_REQUEST T0 ON T.'AP_CACHED_REQUEST_ID'=T0.'_id'");
			builder.append(' ');
			selectDeep = builder.toString();
		}
		return selectDeep;
	}

	protected CapitalMarketsRevenue loadCurrentDeep(Cursor cursor, boolean lock) {
		CapitalMarketsRevenue entity = loadCurrent(cursor, 0, lock);
		int offset = getAllColumns().length;

		APCachedRequest aPCachedRequest = loadCurrentOther(
				daoSession.getAPCachedRequestDao(), cursor, offset);
		entity.setAPCachedRequest(aPCachedRequest);

		return entity;
	}

	public CapitalMarketsRevenue loadDeep(Long key) {
		assertSinglePk();
		if (key == null) {
			return null;
		}

		StringBuilder builder = new StringBuilder(getSelectDeep());
		builder.append("WHERE ");
		SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
		String sql = builder.toString();

		String[] keyArray = new String[]{key.toString()};
		Cursor cursor = db.rawQuery(sql, keyArray);

		try {
			boolean available = cursor.moveToFirst();
			if (!available) {
				return null;
			} else if (!cursor.isLast()) {
				throw new IllegalStateException(
						"Expected unique result, but count was "
								+ cursor.getCount());
			}
			return loadCurrentDeep(cursor, true);
		} finally {
			cursor.close();
		}
	}

	/** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
	public List<CapitalMarketsRevenue> loadAllDeepFromCursor(Cursor cursor) {
		int count = cursor.getCount();
		List<CapitalMarketsRevenue> list = new ArrayList<CapitalMarketsRevenue>(
				count);

		if (cursor.moveToFirst()) {
			if (identityScope != null) {
				identityScope.lock();
				identityScope.reserveRoom(count);
			}
			try {
				do {
					list.add(loadCurrentDeep(cursor, false));
				} while (cursor.moveToNext());
			} finally {
				if (identityScope != null) {
					identityScope.unlock();
				}
			}
		}
		return list;
	}

	protected List<CapitalMarketsRevenue> loadDeepAllAndCloseCursor(
			Cursor cursor) {
		try {
			return loadAllDeepFromCursor(cursor);
		} finally {
			cursor.close();
		}
	}

	/** A raw-style query where you can pass any WHERE clause and arguments. */
	public List<CapitalMarketsRevenue> queryDeep(String where,
			String... selectionArg) {
		Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
		return loadDeepAllAndCloseCursor(cursor);
	}

}
