package com.anypresence.anypresence_inc.citi_mobile_challenge.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.anypresence.anypresence_inc.citi_mobile_challenge.dao.RetailBankingForeignCurrency;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RETAILBANKINGFOREIGNCURRENCIES.
 */
public class RetailBankingForeignCurrencyDao
		extends
			AbstractDao<RetailBankingForeignCurrency, Long> {

	public static final String TABLENAME = "RETAILBANKINGFOREIGNCURRENCIES";

	/**
	 * Properties of entity RetailBankingForeignCurrency.<br/>
	 * Can be used for QueryBuilder and for referencing column names.
	 */
	public static class Properties {
		public final static Property Id = new Property(0, Long.class, "id",
				true, "_id");
		public final static Property FromCurrency = new Property(1,
				String.class, "fromCurrency", false, "FROM_CURRENCY");
		public final static Property Rate = new Property(2, Float.class,
				"rate", false, "RATE");
		public final static Property ToCurrency = new Property(3, String.class,
				"toCurrency", false, "TO_CURRENCY");
		public final static Property Scope = new Property(4, String.class,
				"scope", false, "SCOPE");
		public final static Property ObjectId = new Property(5, String.class,
				"objectId", false, "OBJECT_ID");
		public final static Property _cacheUpdatedAt = new Property(6,
				java.util.Date.class, "_cacheUpdatedAt", false,
				"_CACHE_UPDATED_AT");
		public final static Property ApCachedRequestId = new Property(7,
				Long.class, "apCachedRequestId", false, "AP_CACHED_REQUEST_ID");
	};

	private DaoSession daoSession;

	public RetailBankingForeignCurrencyDao(DaoConfig config) {
		super(config);
	}

	public RetailBankingForeignCurrencyDao(DaoConfig config,
			DaoSession daoSession) {
		super(config, daoSession);
		this.daoSession = daoSession;
	}

	/** Creates the underlying database table. */
	public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint
				+ "'RETAILBANKINGFOREIGNCURRENCIES' (" + //
				"'_id' INTEGER PRIMARY KEY ," + // 0: id
				"'FROM_CURRENCY' TEXT," + // 1: fromCurrency
				"'RATE' REAL," + // 2: rate
				"'TO_CURRENCY' TEXT," + // 3: toCurrency
				"'SCOPE' TEXT," + // 4: scope
				"'OBJECT_ID' TEXT," + // 5: objectId
				"'_CACHE_UPDATED_AT' INTEGER," + // 6: _cacheUpdatedAt
				"'AP_CACHED_REQUEST_ID' INTEGER);"); // 7: apCachedRequestId
		// Add Indexes
		db.execSQL("CREATE UNIQUE INDEX "
				+ constraint
				+ "IDX_RETAILBANKINGFOREIGNCURRENCIES_OBJECT_ID ON RETAILBANKINGFOREIGNCURRENCIES"
				+ " (OBJECT_ID);");
	}

	/** Drops the underlying database table. */
	public static void dropTable(SQLiteDatabase db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "")
				+ "'RETAILBANKINGFOREIGNCURRENCIES'";
		db.execSQL(sql);
	}

	/** @inheritdoc */
	@Override
	protected void bindValues(SQLiteStatement stmt,
			RetailBankingForeignCurrency entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		String fromCurrency = entity.getFromCurrency();
		if (fromCurrency != null) {
			stmt.bindString(2, fromCurrency);
		}

		Float rate = entity.getRate();
		if (rate != null) {
			stmt.bindDouble(3, rate);
		}

		String toCurrency = entity.getToCurrency();
		if (toCurrency != null) {
			stmt.bindString(4, toCurrency);
		}

		String scope = entity.getScope();
		if (scope != null) {
			stmt.bindString(5, scope);
		}

		String objectId = entity.getObjectId();
		if (objectId != null) {
			stmt.bindString(6, objectId);
		}

		java.util.Date _cacheUpdatedAt = entity.get_cacheUpdatedAt();
		if (_cacheUpdatedAt != null) {
			stmt.bindLong(7, _cacheUpdatedAt.getTime());
		}

		Long apCachedRequestId = entity.getApCachedRequestId();
		if (apCachedRequestId != null) {
			stmt.bindLong(8, apCachedRequestId);
		}
	}

	@Override
	protected void attachEntity(RetailBankingForeignCurrency entity) {
		super.attachEntity(entity);
		entity.__setDaoSession(daoSession);
	}

	/** @inheritdoc */
	@Override
	public Long readKey(Cursor cursor, int offset) {
		return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
	}

	/** @inheritdoc */
	@Override
	public RetailBankingForeignCurrency readEntity(Cursor cursor, int offset) {
		RetailBankingForeignCurrency entity = new RetailBankingForeignCurrency(
				//
				cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
				cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // fromCurrency
				cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2), // rate
				cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // toCurrency
				cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // scope
				cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // objectId
				cursor.isNull(offset + 6) ? null : new java.util.Date(cursor
						.getLong(offset + 6)), // _cacheUpdatedAt
				cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // apCachedRequestId
		);
		return entity;
	}

	/** @inheritdoc */
	@Override
	public void readEntity(Cursor cursor, RetailBankingForeignCurrency entity,
			int offset) {
		entity.setId(cursor.isNull(offset + 0) ? null : cursor
				.getLong(offset + 0));
		entity.setFromCurrency(cursor.isNull(offset + 1) ? null : cursor
				.getString(offset + 1));
		entity.setRate(cursor.isNull(offset + 2) ? null : cursor
				.getFloat(offset + 2));
		entity.setToCurrency(cursor.isNull(offset + 3) ? null : cursor
				.getString(offset + 3));
		entity.setScope(cursor.isNull(offset + 4) ? null : cursor
				.getString(offset + 4));
		entity.setObjectId(cursor.isNull(offset + 5) ? null : cursor
				.getString(offset + 5));
		entity.set_cacheUpdatedAt(cursor.isNull(offset + 6)
				? null
				: new java.util.Date(cursor.getLong(offset + 6)));
		entity.setApCachedRequestId(cursor.isNull(offset + 7) ? null : cursor
				.getLong(offset + 7));
	}

	/** @inheritdoc */
	@Override
	protected Long updateKeyAfterInsert(RetailBankingForeignCurrency entity,
			long rowId) {
		entity.setId(rowId);
		return rowId;
	}

	/** @inheritdoc */
	@Override
	public Long getKey(RetailBankingForeignCurrency entity) {
		if (entity != null) {
			return entity.getId();
		} else {
			return null;
		}
	}

	/** @inheritdoc */
	@Override
	protected boolean isEntityUpdateable() {
		return true;
	}

	private String selectDeep;

	protected String getSelectDeep() {
		if (selectDeep == null) {
			StringBuilder builder = new StringBuilder("SELECT ");
			SqlUtils.appendColumns(builder, "T", getAllColumns());
			builder.append(',');
			SqlUtils.appendColumns(builder, "T0", daoSession
					.getAPCachedRequestDao().getAllColumns());
			builder.append(" FROM RETAILBANKINGFOREIGNCURRENCIES T");
			builder.append(" LEFT JOIN APCACHED_REQUEST T0 ON T.'AP_CACHED_REQUEST_ID'=T0.'_id'");
			builder.append(' ');
			selectDeep = builder.toString();
		}
		return selectDeep;
	}

	protected RetailBankingForeignCurrency loadCurrentDeep(Cursor cursor,
			boolean lock) {
		RetailBankingForeignCurrency entity = loadCurrent(cursor, 0, lock);
		int offset = getAllColumns().length;

		APCachedRequest aPCachedRequest = loadCurrentOther(
				daoSession.getAPCachedRequestDao(), cursor, offset);
		entity.setAPCachedRequest(aPCachedRequest);

		return entity;
	}

	public RetailBankingForeignCurrency loadDeep(Long key) {
		assertSinglePk();
		if (key == null) {
			return null;
		}

		StringBuilder builder = new StringBuilder(getSelectDeep());
		builder.append("WHERE ");
		SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
		String sql = builder.toString();

		String[] keyArray = new String[]{key.toString()};
		Cursor cursor = db.rawQuery(sql, keyArray);

		try {
			boolean available = cursor.moveToFirst();
			if (!available) {
				return null;
			} else if (!cursor.isLast()) {
				throw new IllegalStateException(
						"Expected unique result, but count was "
								+ cursor.getCount());
			}
			return loadCurrentDeep(cursor, true);
		} finally {
			cursor.close();
		}
	}

	/** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
	public List<RetailBankingForeignCurrency> loadAllDeepFromCursor(
			Cursor cursor) {
		int count = cursor.getCount();
		List<RetailBankingForeignCurrency> list = new ArrayList<RetailBankingForeignCurrency>(
				count);

		if (cursor.moveToFirst()) {
			if (identityScope != null) {
				identityScope.lock();
				identityScope.reserveRoom(count);
			}
			try {
				do {
					list.add(loadCurrentDeep(cursor, false));
				} while (cursor.moveToNext());
			} finally {
				if (identityScope != null) {
					identityScope.unlock();
				}
			}
		}
		return list;
	}

	protected List<RetailBankingForeignCurrency> loadDeepAllAndCloseCursor(
			Cursor cursor) {
		try {
			return loadAllDeepFromCursor(cursor);
		} finally {
			cursor.close();
		}
	}

	/** A raw-style query where you can pass any WHERE clause and arguments. */
	public List<RetailBankingForeignCurrency> queryDeep(String where,
			String... selectionArg) {
		Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
		return loadDeepAllAndCloseCursor(cursor);
	}

}
