package com.anypresence.sdk.cache.greendao;

//
//  CapitalMarketsContentServiceHelper.java
//  
//
//  Generated by AnyPresence, Inc on 2015-09-15
//  Copyright (c) 2015. All rights reserved.
//

import de.greenrobot.dao.query.*;
import de.greenrobot.dao.*;
import com.anypresence.sdk.acl.*;
import com.anypresence.sdk.callbacks.*;
import com.anypresence.sdk.query.*;
import com.anypresence.sdk.APSDKSetup;
import java.lang.reflect.*;
import com.anypresence.sdk.cache.*;
import com.anypresence.sdk.cache.internal.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.anypresence.sdk.cache.internal.*;
import com.anypresence.sdk.cache.internal.APObjectsAPCachedRequests;
import com.anypresence.anypresence_inc.citi_mobile_challenge.dao.DaoMaster;
import com.anypresence.anypresence_inc.citi_mobile_challenge.dao.DaoSession;
import android.database.sqlite.SQLiteDatabase;
import com.anypresence.sdk.citi_mobile_challenge.models.*;
import com.anypresence.rails_droid.*;
import com.anypresence.sdk.config.Config;
import com.anypresence.sdk.citi_mobile_challenge.models.*;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

import static com.anypresence.sdk.config.Config.DEBUG_MODE;

import java.util.*;

/**
 *
 * GreenDAO helper for <tt>CapitalMarketsContentService</tt>.
 *
 */
class CapitalMarketsContentServiceHelper implements IGreenDAOHelper {
	private static Log log = LogFactory
			.getLog(CapitalMarketsContentServiceHelper.class);

	public com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APObject createObject(
			com.anypresence.sdk.IAPObject object) {
		com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService _object = CapitalMarketsContentServiceHelper
				.copyToDao((com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService) object);
		if (object.getObjectId() != null) {
			_object.setObjectId(object.getObjectId().stringify());
		}

		// Set update time
		_object.set_cacheUpdatedAt(new Date());

		return _object;
	}

	/**
	 * <p>
	 * Gets the <tt>CapitalMarketsContentService</tt> objects from the cache by object id on the provided object.
	 * </p>
	 * 
	 * <p>The LazyList list that is returned must be closed as well<p>
	 * {@code
	 * ((LazyList)list).close();
	 * }
	 *
	 * @return a LazyList list of objects if <tt>object</tt> is not null, otherwise, it returns null.
	 */
	public List<? extends com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APObject> getObjectsByObjectId(
			com.anypresence.sdk.IAPObject object) {
		if (object == null)
			return null;

		return ((DaoSession) CacheManager.getInstance().getDAOSession()
				.getRaw())
				.getCapitalMarketsContentServiceDao()
				.queryBuilder()
				.where(com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentServiceDao.Properties.ObjectId
						.eq(object.getObjectId().stringify())).listLazy();
	}

	public Long insertObject(
			com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APObject object) {
		if (Config.getInstance().getCacheStrategy() == Config.CacheStrategy.OVERWRITE) {
			return ((DaoSession) CacheManager.getInstance().getDAOSession()
					.getRaw())
					.getCapitalMarketsContentServiceDao()
					.insertOrReplace(
							(com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService) object);
		}

		return ((DaoSession) CacheManager.getInstance().getDAOSession()
				.getRaw())
				.getCapitalMarketsContentServiceDao()
				.insert((com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService) object);
	}

	public void updateObject(com.anypresence.sdk.IAPObject object) {

		List<? extends com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APObject> objects = getObjectsByObjectId(object);
		try {
			if ((objects != null) && !objects.isEmpty()) {
				com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService _object = (com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService) objects
						.get(0);

				_object.update();
			}
		} finally {
			if (objects != null) {
				((LazyList) objects).close();
			}
		}
	}

	public void updateEachObject(
			com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APObject object,
			IAPCachedRequest request,
			List<? extends com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APObject> existingObjects) {
		for (com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService tobject : (List<com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService>) existingObjects) {
			try {
				Long origId = tobject.getId();
				Utilities.shallowCopyObjects(tobject, object);
				tobject.setId(origId);
				tobject.setAPCachedRequest(((com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APCachedRequest) request
						.getRaw()));
				((DaoSession) CacheManager.getInstance().getDAOSession()
						.getRaw()).getCapitalMarketsContentServiceDao().update(
						tobject);
				CacheManager
						.getInstance()
						.addToAPCachedRequests(
								tobject.getId(),
								((com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APCachedRequest) request
										.getRaw()).getId());
				if (DEBUG_MODE) {
					log.info(ReflectionToStringBuilder.toString(tobject));
				}
			} catch (CopyException e) {
				//
			}
		}
	}

	public void deleteAllInCacheWithObjectIdPredicate(String objectId) {
		((DaoSession) CacheManager.getInstance().getDAOSession().getRaw())
				.getCapitalMarketsContentServiceDao()
				.queryBuilder()
				.where(com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentServiceDao.Properties.ObjectId
						.eq(objectId)).buildDelete()
				.executeDeleteWithoutDetachingEntities();
	}

	@Deprecated
	public void deleteAllInCacheWithScopePredicate(String scope) {
		((DaoSession) CacheManager.getInstance().getDAOSession().getRaw())
				.getCapitalMarketsContentServiceDao()
				.queryBuilder()
				.where(com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentServiceDao.Properties.Scope
						.eq(scope)).buildDelete()
				.executeDeleteWithoutDetachingEntities();
	}

	public <T extends com.anypresence.sdk.IAPObject> List<T> fetchInCacheWithAPCachedRequestPredicate(
			IAPCachedRequest request) {
		List<T> objects = new ArrayList<T>();
		String query = ", APOBJECTS_APCACHED_REQUESTS R WHERE T._ID=R.AP_OBJECT_ID AND R.AP_CACHED_REQUEST_ID=?";

		List<com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService> cachedObjects = ((DaoSession) CacheManager
				.getInstance().getDAOSession().getRaw())
				.getCapitalMarketsContentServiceDao()
				.queryRawCreate(
						query,
						((com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APCachedRequest) request
								.getRaw()).getId()).listLazy();

		objects.addAll((List<T>) getCloneObjects(cachedObjects));
		return objects;
	}

	public <T extends com.anypresence.sdk.IAPObject> List<T> fetchInCacheWithPredicates(
			Map<String, String> predicates) {
		return fetchInCacheWithScopePredicate(null, predicates, null, null);
	}

	public <T extends com.anypresence.sdk.IAPObject> List<T> fetchInCacheWithObjectIdPredicate(
			String objectId) {
		List<T> objects = new ArrayList<T>();
		List<com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService> cachedObjects = ((DaoSession) CacheManager
				.getInstance().getDAOSession().getRaw())
				.getCapitalMarketsContentServiceDao()
				.queryBuilder()
				.where(com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentServiceDao.Properties.ObjectId
						.eq(objectId)).listLazy();

		objects.addAll((List<T>) getCloneObjects(cachedObjects));
		return objects;
	}

	public <T extends com.anypresence.sdk.IAPObject> List<T> fetchInCacheWithScopePredicate(
			String scope, Map<String, String> params, Integer offset,
			Integer limit) {
		List<T> objects = new ArrayList<T>();

		if (!isDaoSetup()) {
			return objects;
		}

		Map<String, String> whereApCachedRequestsMap = new HashMap<String, String>();
		if (scope != null) {
			whereApCachedRequestsMap.put("Scope", scope);
		}
		List<WhereCondition> whereApCachedRequests = new ArrayList<WhereCondition>();
		GreenDAOUtility.processAPCachedRequestParams(whereApCachedRequests,
				whereApCachedRequestsMap);

		List<com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APCachedRequest> apCachedRequests = ((DaoSession) CacheManager
				.getInstance().getDAOSession().getRaw())
				.getAPCachedRequestDao()
				.queryBuilder()
				.where(com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APCachedRequestDao.Properties.Type
						.eq(com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService.class
								.getSimpleName().toLowerCase()),
						whereApCachedRequests.toArray(new WhereCondition[0]))
				.orderDesc(
						com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APCachedRequestDao.Properties._cacheUpdatedAt)
				.listLazy();

		if (DEBUG_MODE) {
			log.info("There are " + apCachedRequests.size()
					+ " APCachedRequests");
		}
		for (com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APCachedRequest latestAPCachedRequest : apCachedRequests) {
			log.info("  APCachedRequests "
					+ ReflectionToStringBuilder
							.reflectionToString(latestAPCachedRequest));
		}
		try {
			if (apCachedRequests != null && !apCachedRequests.isEmpty()) {
				List<com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APObjectsAPCachedRequests> apObjectsApCachedRequests = null;
				if (scope != null) {
					String query = " WHERE T.AP_CACHED_REQUEST_ID IN (SELECT R._ID FROM APCACHED_REQUEST R WHERE R.TYPE=? AND R.SCOPE=? ORDER BY R._CACHE_UPDATED_AT DESC LIMIT 1) ";
					apObjectsApCachedRequests = ((DaoSession) CacheManager
							.getInstance().getDAOSession().getRaw())
							.getAPObjectsAPCachedRequestsDao()
							.queryRawCreate(
									query,
									com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService.class
											.getSimpleName().toLowerCase(),
									scope).listLazy();
				} else {
					String query = " WHERE T.AP_CACHED_REQUEST_ID IN (SELECT R._ID FROM APCACHED_REQUEST R WHERE R.TYPE=? ORDER BY R._CACHE_UPDATED_AT DESC LIMIT 1) ";
					apObjectsApCachedRequests = ((DaoSession) CacheManager
							.getInstance().getDAOSession().getRaw())
							.getAPObjectsAPCachedRequestsDao()
							.queryRawCreate(
									query,
									com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService.class
											.getSimpleName().toLowerCase())
							.listLazy();
				}
				try {
					if (DEBUG_MODE) {
						for (com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APObjectsAPCachedRequests r : apObjectsApCachedRequests) {
							log.info("Searching in cache with: (scope="
									+ scope
									+ "),(apObjectsApCachedRequests="
									+ ReflectionToStringBuilder
											.reflectionToString(r));
						}
					}
					StringBuilder queryString = new StringBuilder();
					boolean hasInvalidParam = false;
					if (params != null) {
						hasInvalidParam = processParamsIntoStringBuffer(
								queryString, params);
					}

					try {
						Query<com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService> query = null;
						if (!hasInvalidParam
								&& !apObjectsApCachedRequests.isEmpty()) {
							com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APObjectsAPCachedRequests apObjectsApCachedRequest = apObjectsApCachedRequests
									.get(0);
							String rawQuery = ", APOBJECTS_APCACHED_REQUESTS AR WHERE AR.AP_OBJECT_ID=T._ID AND AR.AP_CACHED_REQUEST_ID=?  ";
							if (!queryString.toString().isEmpty()) {
								rawQuery += " AND " + queryString.toString();
							}

							if (limit != null) {
								rawQuery += " LIMIT=" + limit.toString();
							}

							if (offset != null) {
								rawQuery += " OFFSET=" + offset.toString();
							}

							if (DEBUG_MODE) {
								log.info("Raw query: " + rawQuery);
							}

							query = ((DaoSession) CacheManager.getInstance()
									.getDAOSession().getRaw())
									.getCapitalMarketsContentServiceDao()
									.queryRawCreate(
											rawQuery,
											apObjectsApCachedRequest
													.getApCachedRequestId());

							objects.addAll((List<T>) getCloneObjects(query
									.listLazyUncached()));
						}
					} catch (Exception e) {
						log.error(
								"Unable to query for data: " + e.getMessage(),
								e);
					}
				} finally {
					((LazyList) apObjectsApCachedRequests).close();
				}
			}
		} finally {
			((LazyList) apCachedRequests).close();
		}

		return objects;
	}

	public <T extends com.anypresence.sdk.IAPObject> List<T> fetchInCacheWithIds(
			Set<Long> objectIds) {
		QueryBuilder<com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService> queryBuilder = ((DaoSession) CacheManager
				.getInstance().getDAOSession().getRaw())
				.getCapitalMarketsContentServiceDao()
				.queryBuilder()
				.where(com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentServiceDao.Properties.Id
						.in(objectIds));
		return (List<T>) getCloneObjects(queryBuilder.listLazy());
	}

	public <T extends com.anypresence.sdk.IAPObject> List<T> loadAllInCache() {
		List<T> objects = new ArrayList<T>();
		if (!isDaoSetup()) {
			return objects;
		}
		objects.addAll((List<T>) getCloneObjects(((DaoSession) CacheManager
				.getInstance().getDAOSession().getRaw())
				.getCapitalMarketsContentServiceDao().queryBuilder().listLazy()));
		return objects;
	}

	/**
	 * Copies provided DAO object.
	 */
	public static final com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService copyFromDao(
			com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService orig) {
		final com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService newObject = new com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService();

		if (orig.getObjectId() != null)
			newObject.setObjectIdAsString(orig.getObjectId().toString());

		if (orig.getAlertDate() != null)
			newObject.setAlertDate(orig.getAlertDate().toString());

		if (orig.getAllAttachments() != null)
			newObject
					.setAllAttachments(GreenDAOUtility
							.deserializeToArrayList(orig.getAllAttachments()
									.toString()));

		if (orig.getAnalystId() != null)
			newObject.setAnalystId(orig.getAnalystId().toString());

		if (orig.getAnalystType() != null)
			newObject.setAnalystType(orig.getAnalystType().toString());

		if (orig.getAssetClass() != null)
			newObject.setAssetClass(orig.getAssetClass().toString());

		if (orig.getAttachmentId() != null)
			newObject.setAttachmentId(new Integer(orig.getAttachmentId()
					.toString()));

		if (orig.getAuthorDetails() != null)
			newObject
					.setAuthorDetails(GreenDAOUtility
							.deserializeToArrayList(orig.getAuthorDetails()
									.toString()));

		if (orig.getAuthorId() != null)
			newObject.setAuthorId(orig.getAuthorId().toString());

		if (orig.getAuthorName() != null)
			newObject.setAuthorName(orig.getAuthorName().toString());

		if (orig.getAuthors() != null)
			newObject.setAuthors(orig.getAuthors().toString());

		if (orig.getCompany() != null)
			newObject.setCompany(orig.getCompany().toString());

		if (orig.getContentServicesType() != null)
			newObject.setContentServicesType(orig.getContentServicesType()
					.toString());

		if (orig.getContentType() != null)
			newObject.setContentType(orig.getContentType().toString());

		if (orig.getContentUrl() != null)
			newObject.setContentUrl(orig.getContentUrl().toString());

		if (orig.getDateString() != null)
			newObject.setDateString(orig.getDateString().toString());

		if (orig.getDocumentUrl() != null)
			newObject.setDocumentUrl(orig.getDocumentUrl().toString());

		if (orig.getEncryptedId() != null)
			newObject.setEncryptedId(orig.getEncryptedId().toString());

		if (orig.getFileLink() != null)
			newObject.setFileLink(orig.getFileLink().toString());

		if (orig.getFileName() != null)
			newObject.setFileName(orig.getFileName().toString());

		if (orig.getFileType() != null)
			newObject.setFileType(orig.getFileType().toString());

		if (orig.getFormatedPubDate() != null)
			newObject.setFormatedPubDate(orig.getFormatedPubDate().toString());

		if (orig.getFormattedDateStr() != null)
			newObject
					.setFormattedDateStr(orig.getFormattedDateStr().toString());

		if (orig.getHeadline() != null)
			newObject.setHeadline(orig.getHeadline().toString());

		if (orig.getHitCount() != null)
			newObject.setHitCount(new Integer(orig.getHitCount().toString()));

		if (orig.getHtmlEscapedTitle() != null)
			newObject
					.setHtmlEscapedTitle(orig.getHtmlEscapedTitle().toString());

		if (orig.getImage() != null)
			newObject.setImage(orig.getImage().toString());

		if (orig.getImageGroup() != null)
			newObject.setImageGroup(GreenDAOUtility.deserializeToArrayList(orig
					.getImageGroup().toString()));

		if (orig.getKv() != null)
			newObject.setKv(orig.getKv().toString());

		if (orig.getMedialUrlIos() != null)
			newObject.setMedialUrlIos(orig.getMedialUrlIos().toString());

		if (orig.getMediaUrlAndroid() != null)
			newObject.setMediaUrlAndroid(orig.getMediaUrlAndroid().toString());

		if (orig.getMenuCode() != null)
			newObject.setMenuCode(orig.getMenuCode().toString());

		if (orig.getMiliseconds() != null)
			newObject.setMiliseconds(orig.getMiliseconds().toString());

		if (orig.getOboFirstName() != null)
			newObject.setOboFirstName(orig.getOboFirstName().toString());

		if (orig.getOboLastName() != null)
			newObject.setOboLastName(orig.getOboLastName().toString());

		if (orig.getOboPreferredName() != null)
			newObject
					.setOboPreferredName(orig.getOboPreferredName().toString());

		if (orig.getPageCount() != null)
			newObject.setPageCount(new Integer(orig.getPageCount().toString()));

		if (orig.getProductList() != null)
			newObject.setProductList(GreenDAOUtility
					.deserializeToArrayList(orig.getProductList().toString()));

		if (orig.getProductType() != null)
			newObject.setProductType(orig.getProductType().toString());

		if (orig.getPubDate() != null)
			newObject.setPubDate(orig.getPubDate().toString());

		if (orig.getPubId() != null)
			newObject.setPubId(orig.getPubId().toString());

		if (orig.getPubKey() != null)
			newObject.setPubKey(orig.getPubKey().toString());

		if (orig.getRefArticleTitle() != null)
			newObject.setRefArticleTitle(orig.getRefArticleTitle().toString());

		if (orig.getRefArticleUrl() != null)
			newObject.setRefArticleUrl(orig.getRefArticleUrl().toString());

		if (orig.getRegion() != null)
			newObject.setRegion(orig.getRegion().toString());

		if (orig.getResdataUrl() != null)
			newObject.setResdataUrl(orig.getResdataUrl().toString());

		if (orig.getRnum() != null)
			newObject.setRnum(orig.getRnum().toString());

		if (orig.getScale() != null)
			newObject.setScale(GreenDAOUtility.deserializeToArrayList(orig
					.getScale().toString()));

		if (orig.getSectors() != null)
			newObject.setSectors(orig.getSectors().toString());

		if (orig.getSource() != null)
			newObject.setSource(orig.getSource().toString());

		if (orig.getSummary() != null)
			newObject.setSummary(orig.getSummary().toString());

		if (orig.getSynopsis() != null)
			newObject.setSynopsis(orig.getSynopsis().toString());

		if (orig.getTemplate() != null)
			newObject.setTemplate(orig.getTemplate().toString());

		if (orig.getThemeId() != null)
			newObject.setThemeId(orig.getThemeId().toString());

		if (orig.getTickers() != null)
			newObject.setTickers(orig.getTickers().toString());

		if (orig.getTitle() != null)
			newObject.setTitle(orig.getTitle().toString());

		if (orig.getTotalCount() != null)
			newObject
					.setTotalCount(new Integer(orig.getTotalCount().toString()));

		if (orig.getVideoType() != null)
			newObject.setVideoType(orig.getVideoType().toString());

		if (orig.getVideoUrl() != null)
			newObject.setVideoUrl(orig.getVideoUrl().toString());

		return newObject;
	}

	/**
	 * Copies provided object as DAO object.
	 */
	public static final com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService copyToDao(
			com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService orig) {
		final com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService newObject = new com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService();

		if (orig.getId() != null)
			newObject.setObjectId(orig.getId().toString());

		if (orig.getAlertDate() != null)
			newObject.setAlertDate(orig.getAlertDate().toString());

		if (orig.getAllAttachments() != null)
			newObject.setAllAttachments(GreenDAOUtility.serialize(orig
					.getAllAttachments()));

		if (orig.getAnalystId() != null)
			newObject.setAnalystId(orig.getAnalystId().toString());

		if (orig.getAnalystType() != null)
			newObject.setAnalystType(orig.getAnalystType().toString());

		if (orig.getAssetClass() != null)
			newObject.setAssetClass(orig.getAssetClass().toString());

		if (orig.getAttachmentId() != null)
			newObject.setAttachmentId(new Integer(orig.getAttachmentId()));

		if (orig.getAuthorDetails() != null)
			newObject.setAuthorDetails(GreenDAOUtility.serialize(orig
					.getAuthorDetails()));

		if (orig.getAuthorId() != null)
			newObject.setAuthorId(orig.getAuthorId().toString());

		if (orig.getAuthorName() != null)
			newObject.setAuthorName(orig.getAuthorName().toString());

		if (orig.getAuthors() != null)
			newObject.setAuthors(orig.getAuthors().toString());

		if (orig.getCompany() != null)
			newObject.setCompany(orig.getCompany().toString());

		if (orig.getContentServicesType() != null)
			newObject.setContentServicesType(orig.getContentServicesType()
					.toString());

		if (orig.getContentType() != null)
			newObject.setContentType(orig.getContentType().toString());

		if (orig.getContentUrl() != null)
			newObject.setContentUrl(orig.getContentUrl().toString());

		if (orig.getDateString() != null)
			newObject.setDateString(orig.getDateString().toString());

		if (orig.getDocumentUrl() != null)
			newObject.setDocumentUrl(orig.getDocumentUrl().toString());

		if (orig.getEncryptedId() != null)
			newObject.setEncryptedId(orig.getEncryptedId().toString());

		if (orig.getFileLink() != null)
			newObject.setFileLink(orig.getFileLink().toString());

		if (orig.getFileName() != null)
			newObject.setFileName(orig.getFileName().toString());

		if (orig.getFileType() != null)
			newObject.setFileType(orig.getFileType().toString());

		if (orig.getFormatedPubDate() != null)
			newObject.setFormatedPubDate(orig.getFormatedPubDate().toString());

		if (orig.getFormattedDateStr() != null)
			newObject
					.setFormattedDateStr(orig.getFormattedDateStr().toString());

		if (orig.getHeadline() != null)
			newObject.setHeadline(orig.getHeadline().toString());

		if (orig.getHitCount() != null)
			newObject.setHitCount(new Integer(orig.getHitCount()));

		if (orig.getHtmlEscapedTitle() != null)
			newObject
					.setHtmlEscapedTitle(orig.getHtmlEscapedTitle().toString());

		if (orig.getImage() != null)
			newObject.setImage(orig.getImage().toString());

		if (orig.getImageGroup() != null)
			newObject.setImageGroup(GreenDAOUtility.serialize(orig
					.getImageGroup()));

		if (orig.getKv() != null)
			newObject.setKv(orig.getKv().toString());

		if (orig.getMedialUrlIos() != null)
			newObject.setMedialUrlIos(orig.getMedialUrlIos().toString());

		if (orig.getMediaUrlAndroid() != null)
			newObject.setMediaUrlAndroid(orig.getMediaUrlAndroid().toString());

		if (orig.getMenuCode() != null)
			newObject.setMenuCode(orig.getMenuCode().toString());

		if (orig.getMiliseconds() != null)
			newObject.setMiliseconds(orig.getMiliseconds().toString());

		if (orig.getOboFirstName() != null)
			newObject.setOboFirstName(orig.getOboFirstName().toString());

		if (orig.getOboLastName() != null)
			newObject.setOboLastName(orig.getOboLastName().toString());

		if (orig.getOboPreferredName() != null)
			newObject
					.setOboPreferredName(orig.getOboPreferredName().toString());

		if (orig.getPageCount() != null)
			newObject.setPageCount(new Integer(orig.getPageCount()));

		if (orig.getProductList() != null)
			newObject.setProductList(GreenDAOUtility.serialize(orig
					.getProductList()));

		if (orig.getProductType() != null)
			newObject.setProductType(orig.getProductType().toString());

		if (orig.getPubDate() != null)
			newObject.setPubDate(orig.getPubDate().toString());

		if (orig.getPubId() != null)
			newObject.setPubId(orig.getPubId().toString());

		if (orig.getPubKey() != null)
			newObject.setPubKey(orig.getPubKey().toString());

		if (orig.getRefArticleTitle() != null)
			newObject.setRefArticleTitle(orig.getRefArticleTitle().toString());

		if (orig.getRefArticleUrl() != null)
			newObject.setRefArticleUrl(orig.getRefArticleUrl().toString());

		if (orig.getRegion() != null)
			newObject.setRegion(orig.getRegion().toString());

		if (orig.getResdataUrl() != null)
			newObject.setResdataUrl(orig.getResdataUrl().toString());

		if (orig.getRnum() != null)
			newObject.setRnum(orig.getRnum().toString());

		if (orig.getScale() != null)
			newObject.setScale(GreenDAOUtility.serialize(orig.getScale()));

		if (orig.getSectors() != null)
			newObject.setSectors(orig.getSectors().toString());

		if (orig.getSource() != null)
			newObject.setSource(orig.getSource().toString());

		if (orig.getSummary() != null)
			newObject.setSummary(orig.getSummary().toString());

		if (orig.getSynopsis() != null)
			newObject.setSynopsis(orig.getSynopsis().toString());

		if (orig.getTemplate() != null)
			newObject.setTemplate(orig.getTemplate().toString());

		if (orig.getThemeId() != null)
			newObject.setThemeId(orig.getThemeId().toString());

		if (orig.getTickers() != null)
			newObject.setTickers(orig.getTickers().toString());

		if (orig.getTitle() != null)
			newObject.setTitle(orig.getTitle().toString());

		if (orig.getTotalCount() != null)
			newObject.setTotalCount(new Integer(orig.getTotalCount()));

		if (orig.getVideoType() != null)
			newObject.setVideoType(orig.getVideoType().toString());

		if (orig.getVideoUrl() != null)
			newObject.setVideoUrl(orig.getVideoUrl().toString());

		return newObject;
	}

	private static List<com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService> getCloneObjects(
			List<com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService> objects) {
		List<com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService> clonedObjects = null;
		try {
			clonedObjects = shallowCloneList(objects);
		} finally {
			if (clonedObjects == null) {
				clonedObjects = new ArrayList<com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService>();
			}
		}

		return clonedObjects;
	}

	/**
	 * Perform a shallow clone of list of <tt>com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService</tt>.
	 *
	 * @param objects list of <tt>com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService</tt>.
	 * @return list of <tt>CapitalMarketsContentService</tt>.
	 */
	private static List<com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService> shallowCloneList(
			List<com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService> objects) {
		List<com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService> newObjects = new ArrayList<com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService>();
		try {
			for (com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentService object : objects) {
				com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService newObject = new com.anypresence.sdk.citi_mobile_challenge.models.CapitalMarketsContentService();
				newObject = copyFromDao(object);

				newObject.setAllAttachments((ArrayList<Object>) Utilities
						.transformJsonToObject(GreenDAOUtility
								.base64decode(object.getAllAttachments()),
								ArrayList.class));

				newObject.setAuthorDetails((ArrayList<Object>) Utilities
						.transformJsonToObject(GreenDAOUtility
								.base64decode(object.getAuthorDetails()),
								ArrayList.class));

				newObject.setImageGroup((ArrayList<Object>) Utilities
						.transformJsonToObject(GreenDAOUtility
								.base64decode(object.getImageGroup()),
								ArrayList.class));

				newObject.setProductList((ArrayList<Object>) Utilities
						.transformJsonToObject(GreenDAOUtility
								.base64decode(object.getProductList()),
								ArrayList.class));

				newObject
						.setScale((ArrayList<Object>) Utilities
								.transformJsonToObject(GreenDAOUtility
										.base64decode(object.getScale()),
										ArrayList.class));

				newObjects.add(newObject);
			}
		} finally {
			if (objects != null) {
				((LazyList) objects).close();
			}
		}
		return newObjects;
	}

	private static boolean processParamsIntoStringBuffer(StringBuilder sb,
			Map<String, String> params) {
		for (Map.Entry<String, String> entry : params.entrySet()) {
			if (entry.getValue() == null) {
				continue;
			}
			try {
				// The properties needs to be in camel-case form
				Field field = com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentServiceDao.Properties.class
						.getField(Inflector.camelize(entry.getKey(), true));
				Property property = (Property) field.get(null);

				String parsedString = GreenDAOUtility.parsedValue(
						property.type, entry.getValue());
				if (parsedString == null)
					continue;
				if (!sb.toString().isEmpty()) {
					sb = sb.append(" AND ");
				}
				sb = sb.append(" T."
						+ Inflector.underscore(entry.getKey()).toUpperCase()
						+ "=" + parsedString);
			} catch (SecurityException e) {
				e.printStackTrace();
				return true;
			} catch (NoSuchFieldException e) {
				log.error("The field " + entry.getKey()
						+ " does not map to any property on the model.", e);
				return true;
			} catch (IllegalArgumentException e) {
				e.printStackTrace();
				return true;
			} catch (IllegalAccessException e) {
				e.printStackTrace();
				return true;
			}
		}
		return false;
	}

	private static Boolean processParams(List<WhereCondition> list,
			Map<String, String> params) {
		for (Map.Entry<String, String> entry : params.entrySet()) {
			if (entry.getValue() == null) {
				continue;
			}
			try {
				// The properties needs to be in camel-case form
				Field field = com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CapitalMarketsContentServiceDao.Properties.class
						.getField(Inflector.camelize(entry.getKey(), true));
				WhereCondition eq = GreenDAOUtility.processParams(field,
						entry.getValue());
				if (eq == null)
					continue;
				list.add(eq);
			} catch (SecurityException e) {
				e.printStackTrace();
				return true;
			} catch (NoSuchFieldException e) {
				// log.error("The field " + entry.getKey() + " does not map to any property on the model.", e);
				return true;
			} catch (IllegalArgumentException e) {
				e.printStackTrace();
				return true;
			} catch (IllegalAccessException e) {
				e.printStackTrace();
				return true;
			}
		}
		return false;
	}

	private Boolean isDaoSetup() {
		if (((DaoSession) CacheManager.getInstance().getDAOSession().getRaw())
				.getCapitalMarketsContentServiceDao() == null) {
			log.info("The ORM has not been setup yet.");
			return false;
		}
		return true;
	}
}
