package com.anypresence.sdk.citi_mobile_challenge.models;

//
//  CorporatePaymentsCrossBorderFxQuote.java
//  
//
//  Generated by AnyPresence, Inc on 2015-09-11
//  Copyright (c) 2015. All rights reserved.
//

import com.google.common.util.concurrent.*;
import java.util.*;
import java.util.concurrent.Callable;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.EqualsBuilder;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import java.lang.reflect.Field;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import com.anypresence.rails_droid.*;
import com.anypresence.rails_droid.http.RequestMethod;
import com.anypresence.sdk.acl.*;
import com.anypresence.sdk.callbacks.*;
import com.anypresence.sdk.query.*;
import com.anypresence.sdk.config.Config;
import com.anypresence.sdk.acl.UnauthorizedException;
import com.anypresence.sdk.*;
import com.anypresence.sdk.cache.*;
import com.anypresence.sdk.cache.greendao.*;
import com.anypresence.sdk.parse.*;
import java.net.MalformedURLException;
import com.anypresence.rails_droid.RemoteRailsConfig;
import com.anypresence.rails_droid.http.RouterAdapter;
import com.anypresence.sdk.http.HttpAdapter;
import com.anypresence.sdk.Utility;

import com.jayway.jsonpath.PathNotFoundException;

import static com.anypresence.sdk.config.Config.DEBUG_MODE;
import static com.anypresence.sdk.http.HttpAdapter.JSON;
import static com.anypresence.sdk.http.HttpAdapter.XML;
import static com.anypresence.sdk.http.HttpAdapter.FORM_ENCODED;

/**
 * This class represents a model constructed from the Designer.
 *
 * Fields that are to be serialized into json must be annotated with <tt>@Expose</tt>.
 */
public final class CorporatePaymentsCrossBorderFxQuote
		extends
			com.anypresence.sdk.APObject {
	private static final long serialVersionUID = 1L;

	private static final Log log = LogFactory
			.getLog(CorporatePaymentsCrossBorderFxQuote.class);

	private static final String TAG = "CorporatePaymentsCrossBorderFxQuote";

	/**
	 *  Scope names for CorporatePaymentsCrossBorderFxQuote.
	 */
	public static class Scopes {

		public final static String ALL = "all";

		public final static String EXACT_MATCH = "exact_match";

		public final static String COUNT = "count";

		public final static String COUNT_EXACT_MATCH = "count_exact_match";

	}

	private static QueryScope getScope(String scope) {
		if (getQueryScopes().get(scope) == null) {
			return getQueryScopes().get("all");
		}

		return getQueryScopes().get(scope);
	}

	@SerializedName("requested_on")
	@Expose
	private ObjectId requestedOn;
	// Getter/Setter for the id
	@Override
	public ObjectId getObjectId() {
		return requestedOn;
	}

	@Override
	public void setObjectId(ObjectId id) {
		this.requestedOn = id;
	}

	public ObjectId getRequestedOn() {
		return getObjectId();
	}

	public void setRequestedOn(ObjectId requestedOn) {
		setObjectId(requestedOn);
	}

	public void setRequestedOnAsString(String requestedOn) {
		setObjectId(new ObjectId(requestedOn));
	}

	// Getters/setters for field definitions.

	@SerializedName("from_amount")
	@Expose
	private Float fromAmount;

	public Float getFromAmount() {
		return fromAmount;
	}

	public void setFromAmount(Float fromAmount) {
		this.fromAmount = fromAmount;
	}

	@SerializedName("from_currency")
	@Expose
	private String fromCurrency;

	public String getFromCurrency() {
		return fromCurrency;
	}

	public void setFromCurrency(String fromCurrency) {
		this.fromCurrency = fromCurrency;
	}

	@SerializedName("rate_expiry")
	@Expose
	private String rateExpiry;

	public String getRateExpiry() {
		return rateExpiry;
	}

	public void setRateExpiry(String rateExpiry) {
		this.rateExpiry = rateExpiry;
	}

	@SerializedName("rate_reference")
	@Expose
	private String rateReference;

	public String getRateReference() {
		return rateReference;
	}

	public void setRateReference(String rateReference) {
		this.rateReference = rateReference;
	}

	@SerializedName("requested_by")
	@Expose
	private String requestedBy;

	public String getRequestedBy() {
		return requestedBy;
	}

	public void setRequestedBy(String requestedBy) {
		this.requestedBy = requestedBy;
	}

	@SerializedName("to_amount")
	@Expose
	private Float toAmount;

	public Float getToAmount() {
		return toAmount;
	}

	public void setToAmount(Float toAmount) {
		this.toAmount = toAmount;
	}

	@SerializedName("to_currency")
	@Expose
	private String toCurrency;

	public String getToCurrency() {
		return toCurrency;
	}

	public void setToCurrency(String toCurrency) {
		this.toCurrency = toCurrency;
	}

	@SerializedName("value_date")
	@Expose
	private String valueDate;

	public String getValueDate() {
		return valueDate;
	}

	public void setValueDate(String valueDate) {
		this.valueDate = valueDate;
	}

	/**
	 * Copies provided object.
	 */
	public static final CorporatePaymentsCrossBorderFxQuote copy(
			CorporatePaymentsCrossBorderFxQuote orig) {
		final CorporatePaymentsCrossBorderFxQuote newObject = new CorporatePaymentsCrossBorderFxQuote();

		if (orig.getRequestedOn() != null)
			newObject.setRequestedOn(new ObjectId(orig.getRequestedOn()));

		if (orig.getFromAmount() != null)
			newObject.setFromAmount(new Float(orig.getFromAmount()));

		if (orig.getFromCurrency() != null)
			newObject.setFromCurrency(new String(orig.getFromCurrency()));

		if (orig.getRateExpiry() != null)
			newObject.setRateExpiry(new String(orig.getRateExpiry()));

		if (orig.getRateReference() != null)
			newObject.setRateReference(new String(orig.getRateReference()));

		if (orig.getRequestedBy() != null)
			newObject.setRequestedBy(new String(orig.getRequestedBy()));

		if (orig.getToAmount() != null)
			newObject.setToAmount(new Float(orig.getToAmount()));

		if (orig.getToCurrency() != null)
			newObject.setToCurrency(new String(orig.getToCurrency()));

		if (orig.getValueDate() != null)
			newObject.setValueDate(new String(orig.getValueDate()));

		return newObject;
	}

	// Query scopes
	private static Map<String, QueryScope> queryScopes = new HashMap<String, QueryScope>();

	public void setQueryScopes(Map<String, QueryScope> queryScopes) {
		this.queryScopes = queryScopes;
	}

	public static Map<String, QueryScope> getQueryScopes() {
		return queryScopes;
	}

	static {

		QueryScope queryScopeall = new QueryScope();
		queryScopeall.setName("all");

		queryScopes.put(queryScopeall.getName(), queryScopeall);

		QueryScope queryScopeexact_match = new QueryScope();
		queryScopeexact_match.setName("exact_match");

		queryScopes.put(queryScopeexact_match.getName(), queryScopeexact_match);

		QueryScope queryScopecount = new QueryScope();
		queryScopecount.setName("count");

		queryScopes.put(queryScopecount.getName(), queryScopecount);

		QueryScope queryScopecount_exact_match = new QueryScope();
		queryScopecount_exact_match.setName("count_exact_match");

		queryScopes.put(queryScopecount_exact_match.getName(),
				queryScopecount_exact_match);

	}

	/**
	 * Fetches a <tt>CorporatePaymentsCrossBorderFxQuote</tt> with the provided <tt>objectId</tt>.
	 *
	 * @param objectId the id of the object
	 * @return an instance of <tt>CorporatePaymentsCrossBorderFxQuote</tt>
	 * @throws RemoteRequestException If there are other issues with the request.
	 */
	public static CorporatePaymentsCrossBorderFxQuote fetch(String objectId)
			throws RemoteRequestException {
		RemoteRequest.RemoteRequestBuilder remoteRequestBuilder = RemoteRailsConfig
				.getRouterAdapterByClassOrUseDefaultAdapter(
						CorporatePaymentsCrossBorderFxQuote.class)
				.createRemoteRequestBuilder(RequestMethod.GET,
						CorporatePaymentsCrossBorderFxQuote.class);

		CorporatePaymentsCrossBorderFxQuote object = new CorporatePaymentsCrossBorderFxQuote();
		object.setObjectIdAsString(objectId);

		remoteRequestBuilder.context(object);

		RemoteRequest remoteRequest = remoteRequestBuilder
				.createRemoteRequest();
		remoteRequest = Utility.interpolateRemoteRequest(remoteRequest);

		return com.anypresence.sdk.APObject.fetch(remoteRequest,
				CorporatePaymentsCrossBorderFxQuote.class);
	}

	/**
	 * Fetches a <tt>CorporatePaymentsCrossBorderFxQuote</tt> with the provided <tt>objectId</tt> in the background.
	 *
	 * <p>
	 * The {@link import com.anypresence.sdk.callbacks.APCallback} callback allows you to run code in the main UI thread.
	 * </p>
	 * <p>
	 * Example:
	 * </p>
	 * <pre>
	 * {@code
	 * CorporatePaymentsCrossBorderFxQuote.fetchInBackground("123", new APCallback<CorporatePaymentsCrossBorderFxQuote>() {
	 *     
	 *     public void finished(CorporatePaymentsCrossBorderFxQuote object, Throwable ex) {
	 *         if (ex == null) {
	 *             Log.i(TAG, "Object fetched!");
	 *         } else {
	 *             Log.e(TAG, "Unable to fetch object!", ex);
	 *         }
	 *     }
	 * });
	 * }
	 * </pre>
	 *
	 * @see import com.anypresence.sdk.callbacks.APCallback
	 * @param objectId the id of the object
	 * @param futureCallback the callback that handles the result of the request.
	
	 * @return the cached <tt>CorporatePaymentsCrossBorderFxQuote</tt> if it exists, otherwise, null.
	
	 */
	public static CorporatePaymentsCrossBorderFxQuote

	fetchInBackground(
			String objectId,
			IAPFutureCallback<CorporatePaymentsCrossBorderFxQuote> futureCallback) {

		return com.anypresence.sdk.APObject.fetchInBackground(objectId,
				CorporatePaymentsCrossBorderFxQuote.class, futureCallback);

	}

	/**
	 * Queries for <tt>CorporatePaymentsCrossBorderFxQuote</tt> with the provided <tt>scope</tt>.
	 *
	 * Note: the scopes were defined from the Designer.
	 *
	 * @param scope the scope to perform the query.
	 * @throws RemoteRequestException If there are other issues with the request.
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> query(String scope)
			throws RemoteRequestException {
		return query(scope, null, null, null);
	}

	/**
	 * Queries for <tt>CorporatePaymentsCrossBorderFxQuote</tt> with the provided <tt>scope</tt> and other params.
	 *
	 * Note: the scopes were defined from the Designer.
	 *
	 * @param scope the scope to perform the query.
	 * @param params a map of parameters.
	 * @param offset offset for the query, or <tt>null</tt> for no offset.
	 * @param limit max results to return back, <tt>null</tt> for no limit.
	 * @throws RemoteRequestException If there are other issues with the request.
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> query(String scope,
			Map<String, String> params, Integer offset, Integer limit)
			throws RemoteRequestException {
		RemoteRequest.RemoteRequestBuilder remoteRequestBuilder = RemoteRailsConfig
				.getRouterAdapterByClassOrUseDefaultAdapter(
						CorporatePaymentsCrossBorderFxQuote.class)
				.createRemoteRequestBuilder(scope, RequestMethod.GET,
						CorporatePaymentsCrossBorderFxQuote.class);
		remoteRequestBuilder.query(scope);
		if (params != null) {
			remoteRequestBuilder.addToParameters(params);
			remoteRequestBuilder.context(params);
		}
		if (offset != null) {
			remoteRequestBuilder.addToParameters("offset", offset.toString());
		}

		if (limit != null) {
			remoteRequestBuilder.addToParameters("limit", limit.toString());
		}
		RemoteRequest remoteRequest = remoteRequestBuilder
				.createRemoteRequest();

		return com.anypresence.sdk.APObject.query(remoteRequest, offset, limit,
				CorporatePaymentsCrossBorderFxQuote.class);
	}

	/**
	 * Queries for <tt>CorporatePaymentsCrossBorderFxQuote</tt> with the provided <tt>scope</tt> and other params.
	 *
	 * Note: the scopes were defined from the Designer.
	 *
	 * @param scope the scope to perform the query.
	 * @param params a map of parameters.
	 * @throws RemoteRequestException If there are other issues with the request.
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> query(String scope,
			Map<String, String> params) throws RemoteRequestException {
		return query(scope, params, null, null);
	}

	/**
	 * Queries for <tt>CorporatePaymentsCrossBorderFxQuote</tt> with the provided <tt>scope</tt> and other params.
	 *
	 * Note: the scopes were defined from the Designer.
	 *
	 * @param scope the scope to perform the query.
	 * @param params a map of parameters.
	 * @throws RemoteRequestException If there are other issues with the request.
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> queryInBackground(
			final String scope,
			Map<String, String> params,
			IAPFutureCallback<List<CorporatePaymentsCrossBorderFxQuote>> futureCallback) {

		return queryInBackground(scope, params, null, null, futureCallback);

	}

	/**
	 * Queries for <tt>CorporatePaymentsCrossBorderFxQuote</tt> with the provided <tt>scope</tt> in the background.
	 *
	 * Note: the scopes were defined from the Designer.
	 *
	 * <p>
	 * The {@link import com.anypresence.sdk.callbacks.APCallback} callback allows you to run code in the main UI thread.
	 * </p>
	 * <p>
	 * Example:
	 * </p>
	 * <pre>
	 * {@code
	 * CorporatePaymentsCrossBorderFxQuote.queryInBackground("all", new APCallback<List<CorporatePaymentsCrossBorderFxQuote>>() {
	 *     
	 *     public void finished(List<CorporatePaymentsCrossBorderFxQuote> objects, Throwable ex) {
	 *         if (ex == null) {
	 *             Log.i(TAG, "Objects fetched!");
	 *         } else {
	 *             Log.e(TAG, "Unable to fetch objects!", ex);
	 *         }
	 *     }
	 * });
	 * }
	 * </pre>
	 *
	 * @see import com.anypresence.sdk.callbacks.APCallback
	 * @param scope the scope to perform the query.
	 * @param futureCallback the callback that handles the result of the request.
	 * @return list of cached <tt>CorporatePaymentsCrossBorderFxQuote</tt> objects.
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> queryInBackground(
			String scope,
			IAPFutureCallback<List<CorporatePaymentsCrossBorderFxQuote>> futureCallback) {

		return queryInBackground(scope, null, null, null, futureCallback);

	}

	/**
	 * Queries for <tt>CorporatePaymentsCrossBorderFxQuote</tt> with the provided <tt>scope</tt> in the background.
	 *
	 * Note: the scopes were defined from the Designer.
	 * <p>
	 * The {@link import com.anypresence.sdk.callbacks.APCallback} callback allows you to run code in the main UI thread.
	 * </p>
	 * <p>
	 * Example:
	 * </p>
	 * <pre>
	 * {@code
	 * CorporatePaymentsCrossBorderFxQuote.queryInBackground("all", 0, 25, new APCallback<List<CorporatePaymentsCrossBorderFxQuote>>() {
	 *     
	 *     public void finished(List<CorporatePaymentsCrossBorderFxQuote> objects, Throwable ex) {
	 *         if (ex == null) {
	 *             Log.i(TAG, "Objects fetched!");
	 *         } else {
	 *             Log.e(TAG, "Unable to fetch objects!", ex);
	 *         }
	 *     }
	 * });
	 * }
	 * </pre>
	 *
	 * @see import com.anypresence.sdk.callbacks.APCallback
	 * @param scope the scope to perform the query.
	 * @param offset offset for the query, or <tt>null</tt> for no offset.
	 * @param limit max results to return back, <tt>null</tt> for no limit.
	 * @param futureCallback the callback that handles the result of the request.
	 * @return list of cached <tt>CorporatePaymentsCrossBorderFxQuote</tt> objects.
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> queryInBackground(
			String scope,
			Integer offset,
			Integer limit,
			IAPFutureCallback<List<CorporatePaymentsCrossBorderFxQuote>> futureCallback) {

		return queryInBackground(scope, null, offset, limit, futureCallback);

	}

	/**
	 * Queries for <tt>CorporatePaymentsCrossBorderFxQuote</tt> with the provided <tt>scope</tt> in the background.
	 *
	 * Note: the scopes were defined from the Designer.
	 * <p>
	 * The {@link import com.anypresence.sdk.callbacks.APCallback} callback allows you to run code in the main UI thread.
	 * </p>
	 * <p>
	 * Example:
	 * </p>
	 * <pre>
	 * {@code
	 * Map<String,String> params = new HashMap<String,String>();
	 * params.put("name", "test");
	 * CorporatePaymentsCrossBorderFxQuote.queryInBackground("all", params, 0, 25, new APCallback<List<CorporatePaymentsCrossBorderFxQuote>>() {
	 *     
	 *     public void finished(List<CorporatePaymentsCrossBorderFxQuote> objects, Throwable ex) {
	 *         if (ex == null) {
	 *             Log.i(TAG, "Objects fetched!");
	 *         } else {
	 *             Log.e(TAG, "Unable to fetch objects!", ex);
	 *         }
	 *     }
	 * });
	 * }
	 * </pre>
	 *
	 * @see import com.anypresence.sdk.callbacks.APCallback
	 * @param scope the scope to perform the query.
	 * @param params a map of parameters.
	 * @param offset offset for the query, or <tt>null</tt> for no offset.
	 * @param limit max results to return back, <tt>null</tt> for no limit.
	 * @param futureCallback the callback that handles the result of the request.
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> queryInBackground(
			final String scope,
			Map<String, String> params,
			Integer offset,
			Integer limit,
			IAPFutureCallback<List<CorporatePaymentsCrossBorderFxQuote>> futureCallback) {

		RemoteRequest.RemoteRequestBuilder remoteRequestBuilder = RemoteRailsConfig
				.getRouterAdapterByClassOrUseDefaultAdapter(
						CorporatePaymentsCrossBorderFxQuote.class)
				.createRemoteRequestBuilder(scope, RequestMethod.GET,
						CorporatePaymentsCrossBorderFxQuote.class);
		remoteRequestBuilder.query(scope);
		if (params != null) {
			remoteRequestBuilder.addToParameters(params);
			remoteRequestBuilder.context(params);
		}

		if (offset != null) {
			remoteRequestBuilder.addToParameters("offset", offset.toString());
		}

		if (limit != null) {
			remoteRequestBuilder.addToParameters("limit", limit.toString());
		}

		RemoteRequest remoteRequest = remoteRequestBuilder
				.createRemoteRequest();

		if (DEBUG_MODE) {
			System.out.println(ReflectionToStringBuilder
					.reflectionToString(remoteRequest));
		}

		return com.anypresence.sdk.APObject.queryInBackground(remoteRequest,
				CorporatePaymentsCrossBorderFxQuote.class, futureCallback);

	}

	/**
	 * Performs aggregate query with the provided <tt>scope</tt>.
	 *
	 * Note: the scopes were defined from the Designer.
	 *
	 * @param scope the scope to perform the query.
	 * @param params a map of parameters.
	 * @throws RemoteRequestException If there are other issues with the request.
	 */
	public static String aggregateQuery(String scope, Map<String, String> params)
			throws RemoteRequestException {
		return com.anypresence.sdk.APObject.aggregateQuery(scope, params,
				CorporatePaymentsCrossBorderFxQuote.class);
	}

	/**
	 * Performs aggregate query with the provided <tt>scope</tt> in the background.
	 *
	 * Note: the scopes were defined from the Designer.
	 * <p>
	 * The {@link import com.anypresence.sdk.callbacks.APCallback} callback allows you to run code in the main UI thread.
	 * </p>
	 * <p>
	 * Example:
	 * </p>
	 * <pre>
	 * {@code
	 * Map<String,String> params = new HashMap<String,String>();
	 * CorporatePaymentsCrossBorderFxQuote.aggregateQueryInBackground("count", params, new APCallback<String>() {
	 *     
	 *     public void finished(String count, Throwable ex) {
	 *         if (ex == null) {
	 *             Log.i(TAG, "success");
	 *         } else {
	 *             Log.e(TAG, "failure", ex);
	 *         }
	 *     }
	 * });
	 * }
	 * </pre>
	 *
	 * @see import com.anypresence.sdk.callbacks.APCallback
	 * @param scope the scope to perform the query.
	 * @param params a map of parameters.
	 * @param futureCallback the callback that handles the result of the request.
	 */
	public static void aggregateQueryInBackground(String scope,
			Map<String, String> params, IAPFutureCallback<String> futureCallback) {
		com.anypresence.sdk.APObject.aggregateQueryInBackground(scope, params,
				CorporatePaymentsCrossBorderFxQuote.class, futureCallback);
	}

	/**
	 * Deletes all data in cache for <tt>CorporatePaymentsCrossBorderFxQuote</tt>.
	 */
	public static void deleteAllInCache() {
		com.anypresence.sdk.APObject.deleteAllInCache();
	}

	/**
	 * Loads all <tt>CorporatePaymentsCrossBorderFxQuote</tt> objects in local cache.
	 *
	 * @return list of <tt>CorporatePaymentsCrossBorderFxQuote</tt>
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> loadAllInCache() {
		return com.anypresence.sdk.APSDKSetup.getCacheManager().loadAllInCache(
				CorporatePaymentsCrossBorderFxQuote.class);
	}

	/**
	 * Loads <tt>CorporatePaymentsCrossBorderFxQuote</tt> objects in local cache.
	 *
	 * @param offset the offset
	 * @param limit the limit
	 * @return list of <tt>CorporatePaymentsCrossBorderFxQuote</tt>
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> loadInCache(
			Integer offset, Integer limit) {
		return null;
	}

	/**
	 * Updates object in cache if the object id is not null.
	 */
	public void updateInCache() {
		com.anypresence.sdk.APSDKSetup.getCacheManager().updateInCache(
				CorporatePaymentsCrossBorderFxQuote.class, this);
	}

	/**
	 * Saves object into cache.
	 */
	public void saveInCache() {
		saveInCache(null);
	}

	/**
	 * Saves object into cache with provided scope.
	 */
	public void saveInCache(String scope) {
		com.anypresence.sdk.APSDKSetup.getCacheManager().saveInCache(
				CorporatePaymentsCrossBorderFxQuote.class, this, scope);
	}

	/**
	 * Saves object into cache with provided <tt>APCachedRequest</tt>.
	 */
	public void saveInCacheWithRequest(IAPCachedRequest request) {
		com.anypresence.sdk.APSDKSetup.getCacheManager()
				.saveInCacheWithRequest(
						CorporatePaymentsCrossBorderFxQuote.class, this,
						request);
	}

	/**
	 * Deletes all <tt>CorporatePaymentsCrossBorderFxQuote</tt> objects in cache that has
	 * this instance's object id.
	 */
	public void deleteInCache() {
		if (this.getObjectId() != null) {
			deleteAllInCacheWithObjectIdPredicate(this.getObjectId()
					.stringify());
		} else {
			log.info("Cannot delete in local cache since the objectId is not set");
		}
	}

	/**
	 * Fetches <tt>CorporatePaymentsCrossBorderFxQuote</tt> from cache with provided remote object id.
	 * 
	 * @param objectId the remote object id.
	 * @return a list of <tt>CorporatePaymentsCrossBorderFxQuote</tt>;
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> fetchInCacheWithObjectIdPredicate(
			String objectId) {
		return com.anypresence.sdk.APSDKSetup.getCacheManager()
				.fetchInCacheWithObjectIdPredicate(
						CorporatePaymentsCrossBorderFxQuote.class, objectId);
	}

	/**
	 * Fetches <tt>CorporatePaymentsCrossBorderFxQuote</tt> from cache by searching for requests matching 
	 * the exact scope and parameters provided.
	 * <p>
	 * Example:
	 * </p>
	 * <pre>
	 * {@code
	 * Map<String,String> params = new HashMap<String,String>();
	 * params.put("name", "test");
	 * CorporatePaymentsCrossBorderFxQuote.queryInBackground("all", params, new APCallback<List<CorporatePaymentsCrossBorderFxQuote>>() {
	 *     
	 *     public void finished(List<CorporatePaymentsCrossBorderFxQuote> objects, Throwable ex) {
	 *         if (ex == null) {
	 *             Log.i(TAG, "Objects fetched!");
	 *         } else {
	 *             Log.e(TAG, "Unable to fetch objects!", ex);
	 *         }
	 *     }
	 * });
	 * // Get the cached objects from the above query.
	 * CorporatePaymentsCrossBorderFxQuote.fetchInCacheWithParameterPredicate("all", params);
	 * }
	 *
	 * </pre>
	 * 
	 * @param scope the scope 
	 * @param params the parameter
	 * @return a list of <tt>CorporatePaymentsCrossBorderFxQuote</tt>;
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> fetchInCacheWithParameterPredicate(
			String scope, Map<String, String> params) {
		return com.anypresence.sdk.APSDKSetup.getCacheManager()
				.fetchInCacheWithParameterPredicate(
						CorporatePaymentsCrossBorderFxQuote.class, scope,
						params);
	}

	/**
	 * Fetches <tt>CorporatePaymentsCrossBorderFxQuote</tt> from cache with provided scope.
	 * 
	 * @param scope the scope.
	 * @return a list of <tt>CorporatePaymentsCrossBorderFxQuote</tt>;
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> fetchInCacheWithScopePredicate(
			String scope, Integer offset, Integer limit) {
		return fetchInCacheWithScopePredicate(scope, null, offset, limit);
	}

	/**
	 * Fetches <tt>CorporatePaymentsCrossBorderFxQuote</tt> from cache with provided scope.
	 * 
	 * @param scope the scope.
	 * @return a list of <tt>CorporatePaymentsCrossBorderFxQuote</tt>;
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> fetchInCacheWithScopePredicate(
			String scope) {
		return fetchInCacheWithScopePredicate(scope, null, null);
	}

	/**
	 * Fetches <tt>CorporatePaymentsCrossBorderFxQuote</tt> from cache with provided scope.
	 * 
	 * @param scope the scope
	 * @param params the parameters
	 * @return a list of <tt>CorporatePaymentsCrossBorderFxQuote</tt>;
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> fetchInCacheWithScopePredicate(
			String scope, Map<String, String> params) {
		return fetchInCacheWithScopePredicate(scope, params, null, null);
	}

	/**
	 * Fetches <tt>CorporatePaymentsCrossBorderFxQuote</tt> from cache with provided scope.
	 * 
	 * @param scope the scope.
	 * @param params the parameters
	 * @param offset the offset
	 * @param limit the limit
	 * @return a list of <tt>CorporatePaymentsCrossBorderFxQuote</tt>;
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> fetchInCacheWithScopePredicate(
			String scope, Map<String, String> params, Integer offset,
			Integer limit) {
		return com.anypresence.sdk.APSDKSetup.getCacheManager()
				.fetchInCacheWithScopePredicate(
						CorporatePaymentsCrossBorderFxQuote.class, scope,
						params, offset, limit);
	}

	/**
	 * Fetches <tt>CorporatePaymentsCrossBorderFxQuote</tt> from cache with provided request.
	 * 
	 * @param request instance of <tt>com.anypresence.anypresence_inc.citi_mobile_challenge.dao.APCachedRequest</tt>.
	 * @return a list of <tt>CorporatePaymentsCrossBorderFxQuote</tt>;
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> fetchInCacheWithAPCachedRequestPredicate(
			IAPCachedRequest request) {
		return com.anypresence.sdk.APSDKSetup.getCacheManager()
				.fetchInCacheWithAPCachedRequestPredicate(
						CorporatePaymentsCrossBorderFxQuote.class, request);
	}

	/**
	 * Fetches <tt>CorporatePaymentsCrossBorderFxQuote</tt> from cache with latest request.
	 * 
	 * @param scope the scope to perform the query.
	 * @param params a map of parameters.
	 * @param offset offset for the query, or <tt>null</tt> for no offset.
	 * @param limit max results to return back, <tt>null</tt> for no limit.
	 * @return a list of <tt>CorporatePaymentsCrossBorderFxQuote</tt>;
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> fetchInCacheWithLatestAPCachedRequestPredicate(
			String scope, Map<String, String> params, Integer offset,
			Integer limit) {
		return com.anypresence.sdk.APSDKSetup.getCacheManager()
				.fetchInCacheWithLatestAPCachedRequestPredicate(
						CorporatePaymentsCrossBorderFxQuote.class, scope,
						params, offset, limit);
	}

	/**
	 * Fetches <tt>CorporatePaymentsCrossBorderFxQuote</tt> from cache with predicates.
	 *
	 * @see com.anypresence.anypresence_inc.citi_mobile_challenge.dao.CorporatePaymentsCrossBorderFxQuoteDao.Properties
	 *
	 * @param predicates hash of predicates
	 * @return a list of <tt>CorporatePaymentsCrossBorderFxQuote</tt>
	 */
	public static List<CorporatePaymentsCrossBorderFxQuote> fetchInCacheWithPredicates(
			Map<String, String> predicates) {
		return com.anypresence.sdk.APSDKSetup.getCacheManager()
				.fetchInCacheWithPredicates(
						CorporatePaymentsCrossBorderFxQuote.class, predicates);
	}

	/**
	 * Deletes <tt>CorporatePaymentsCrossBorderFxQuote</tt> from cache matching <tt>objectId</tt>.
	 * 
	 * @param objectId the remote object id.
	 */
	public static void deleteAllInCacheWithObjectIdPredicate(String objectId) {
		com.anypresence.sdk.APSDKSetup.getCacheManager()
				.deleteAllInCacheWithObjectIdPredicate(
						CorporatePaymentsCrossBorderFxQuote.class, objectId);
	}

	/**
	 * Deletes <tt>CorporatePaymentsCrossBorderFxQuote</tt> from cache matching <tt>scope</tt>.
	 * 
	 * @param scope the scope.
	 */
	public static void deleteAllInCacheWithScopePredicate(String scope) {
		com.anypresence.sdk.APSDKSetup.getCacheManager()
				.deleteAllInCacheWithScopePredicate(
						CorporatePaymentsCrossBorderFxQuote.class, scope);
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(17, 37).

		append(requestedOn).

		append(fromAmount).

		append(fromCurrency).

		append(rateExpiry).

		append(rateReference).

		append(requestedBy).

		append(toAmount).

		append(toCurrency).

		append(valueDate).

		append(getObjectId()).toHashCode();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if ((obj == null) || (obj.getClass() != this.getClass()))
			return false;
		CorporatePaymentsCrossBorderFxQuote other = (CorporatePaymentsCrossBorderFxQuote) obj;
		return new EqualsBuilder().

		append(requestedOn, other.requestedOn).

		append(fromAmount, other.fromAmount).

		append(fromCurrency, other.fromCurrency).

		append(rateExpiry, other.rateExpiry).

		append(rateReference, other.rateReference).

		append(requestedBy, other.requestedBy).

		append(toAmount, other.toAmount).

		append(toCurrency, other.toCurrency).

		append(valueDate, other.valueDate).

		append(getObjectId(), other.getObjectId()).isEquals();
	}

	// Backend on Device
	public static String MAPPING = "CorporatePaymentsCrossBorderFxQuote";
	public static String BASE_URL = "";
	public static String PORT = "";
	public static String PREFIX = "";
	public static String QUERY_PREFIX = "";
	public static boolean USE_SUFFIX = false;

	/**
	 * Deprecated: Pulled up into HttpAdapter
	 */
	@Override
	@Deprecated
	public String requestMapping() {
		return MAPPING;
	}

	/**
	 * Deprecated: Pulled up into HttpAdapter
	 */
	@Override
	@Deprecated
	public String requestBaseUrl() throws MalformedURLException {
		return BASE_URL;
	}

	/**
	 * Deprecated: Pulled up into HttpAdapter
	 */
	@Override
	@Deprecated
	public String requestPrefix() {
		return PREFIX;
	}

	/**
	 * Deprecated: Pulled up into HttpAdapter
	 */
	@Deprecated
	public static String requestQueryPrefix() {
		if (QUERY_PREFIX.isEmpty()) {
			return "%s";
		}
		return QUERY_PREFIX + "[%s]";
	}

	@Override
	public String serialize() {
		String bodyFormat = getSerializationBodyFormat();
		SerializerBuilder builder = null;

		String recordSelector = HttpAdapter.createResponseWrangling(this)
				.getRecordSelector();
		if (XML.equals(bodyFormat)) {
			builder = new XmlSerializer.XmlSerializerBuilder(recordSelector);
		} else if (JSON.equals(bodyFormat)) {
			builder = new JsonSerializer.JsonSerializerBuilder(recordSelector);
		} else if (FORM_ENCODED.equals(bodyFormat)) {
			builder = new FormEncodedSerializer.FormEncodedSerializerBuilder(
					recordSelector);
		}

		final RouterAdapter routerAdapter = RemoteRailsConfig
				.getRouterAdapterByClass(this.getClass());
		if (builder != null && routerAdapter != null) {

			builder.addFieldMapping(((HttpAdapter) routerAdapter)
					.getConfigurationsAsConfiguration("POST")
					.getResponseRemoteFieldName("requested_on"), "requested_on");

			builder.addFieldMapping(((HttpAdapter) routerAdapter)
					.getConfigurationsAsConfiguration("POST")
					.getResponseRemoteFieldName("from_amount"), "from_amount");

			builder.addFieldMapping(((HttpAdapter) routerAdapter)
					.getConfigurationsAsConfiguration("POST")
					.getResponseRemoteFieldName("from_currency"),
					"from_currency");

			builder.addFieldMapping(((HttpAdapter) routerAdapter)
					.getConfigurationsAsConfiguration("POST")
					.getResponseRemoteFieldName("rate_expiry"), "rate_expiry");

			builder.addFieldMapping(((HttpAdapter) routerAdapter)
					.getConfigurationsAsConfiguration("POST")
					.getResponseRemoteFieldName("rate_reference"),
					"rate_reference");

			builder.addFieldMapping(((HttpAdapter) routerAdapter)
					.getConfigurationsAsConfiguration("POST")
					.getResponseRemoteFieldName("requested_by"), "requested_by");

			builder.addFieldMapping(((HttpAdapter) routerAdapter)
					.getConfigurationsAsConfiguration("POST")
					.getResponseRemoteFieldName("to_amount"), "to_amount");

			builder.addFieldMapping(((HttpAdapter) routerAdapter)
					.getConfigurationsAsConfiguration("POST")
					.getResponseRemoteFieldName("to_currency"), "to_currency");

			builder.addFieldMapping(((HttpAdapter) routerAdapter)
					.getConfigurationsAsConfiguration("POST")
					.getResponseRemoteFieldName("value_date"), "value_date");

			return builder.create().serialize(this);
		} else {
			return super.serialize();
		}
	}

	@Override
	public ArrayList<RemoteObject> deserializeArray(String queryScope,
			String input) {
		String bodyFormat = getDeserializationBodyFormat();
		if (XML.equals(bodyFormat)) {
			return deserializeArrayAsXml(queryScope, input);
		} else if (JSON.equals(bodyFormat)) {
			return deserializeArrayAsJson(queryScope, input);
		} else {
			return deserializeArrayAsJson(queryScope, input);
		}
	}

	@Override
	public ArrayList<RemoteObject> deserializeArray(String input) {
		return deserializeArray("", input);
	}

	private ArrayList<RemoteObject> deserializeArrayAsXml(String queryScope,
			String input) {
		ArrayList<RemoteObject> objects = new ArrayList<RemoteObject>();

		XmlParser parser = new XmlParser(input);
		XmlElement parent = ((XmlElement) parser.parse(HttpAdapter
				.createResponseWrangling(queryScope, this)
				.getCollectionSelector(), XmlElement.class)).getParent();
		for (int i = 0; i < parent.getChildCount(); i++) {
			objects.add(deserialize(queryScope, new XmlParser(parent.get(i))));
		}

		return objects;
	}

	private ArrayList<RemoteObject> deserializeArrayAsJson(String queryScope,
			String input) {
		ArrayList<RemoteObject> objects = new ArrayList<RemoteObject>();

		JsonParser parser = new JsonParser(input);
		JsonArray parent = ((JsonElement) parser.parse(HttpAdapter
				.createResponseWrangling(queryScope, this)
				.getCollectionSelector(), JsonElement.class)).getAsJsonArray();
		for (int i = 0; i < parent.size(); i++) {
			objects.add(deserialize(queryScope, new JsonParser(parent.get(i))));
		}

		return objects;
	}

	@Override
	public String getDeserializationBodyFormat() {
		final HttpAdapter routerAdapter = (HttpAdapter) RemoteRailsConfig
				.getRouterAdapterByClass(this.getClass());
		if (routerAdapter == null
				|| routerAdapter.getConfigurationsAsConfiguration("GET") == null) {
			return RemoteRailsConfig.getInstance().getDefaultRouterAdapter()
					.getSuffix();
		}
		return routerAdapter.getConfigurationsAsConfiguration("GET")
				.getBodyFormat();
	}

	@Override
	public String getSerializationBodyFormat() {
		final HttpAdapter routerAdapter = (HttpAdapter) RemoteRailsConfig
				.getRouterAdapterByClass(this.getClass());
		if (routerAdapter == null
				|| routerAdapter.getConfigurationsAsConfiguration("GET") == null) {
			return RemoteRailsConfig.getInstance().getDefaultRouterAdapter()
					.getSuffix();
		}
		return routerAdapter.getConfigurationsAsConfiguration("POST")
				.getBodyFormat();
	}

	@Override
	public RemoteObject deserialize(String queryScope, String input) {
		String bodyFormat = getDeserializationBodyFormat();
		// TODO parse role if auth object
		Parser parser = null;
		if (XML.equals(bodyFormat)) {
			parser = createXmlParser(queryScope, input);
		} else if (JSON.equals(bodyFormat)) {
			parser = createJsonParser(queryScope, input);
		} else {
			parser = createJsonParser(queryScope, input);
		}

		return deserialize(queryScope, parser);
	}

	@Override
	public RemoteObject deserialize(String input) {
		return deserialize("", input);
	}

	private Parser createXmlParser(String queryScope, String input) {
		Parser parser = new XmlParser(input);
		if (!HttpAdapter.createResponseWrangling(queryScope, this)
				.getRecordSelector().isEmpty()) {
			((XmlParser) parser).setRootElement(parser.parse(HttpAdapter
					.createResponseWrangling(queryScope, this)
					.getRecordSelector(), XmlElement.class));
		}
		return parser;
	}

	private Parser createJsonParser(String queryScope, String input) {
		Parser parser = new JsonParser(input);
		if (!HttpAdapter.createResponseWrangling(queryScope, this)
				.getRecordSelector().isEmpty()) {
			((JsonParser) parser).setRootElement(parser.parse(HttpAdapter
					.createResponseWrangling(queryScope, this)
					.getRecordSelector(), JsonElement.class));
		}
		return parser;
	}

	public RemoteObject deserialize(String queryScope, Parser parser) {
		final RouterAdapter routerAdapter = RemoteRailsConfig
				.getRouterAdapterByClass(this.getClass());
		CorporatePaymentsCrossBorderFxQuote object = new CorporatePaymentsCrossBorderFxQuote();
		HttpAdapter.Configuration configuration = null;
		if ((routerAdapter != null) && (routerAdapter instanceof HttpAdapter)) {
			if (queryScope != null && !queryScope.isEmpty()) {
				configuration = ((HttpAdapter) routerAdapter)
						.getScopedConfigurationsByNameAsConfiguration(queryScope);
			} else {
				configuration = ((HttpAdapter) routerAdapter)
						.getConfigurationsAsConfiguration("GET");
			}
		}
		if (configuration != null) {

			try {

				object.requestedOn = parser.parse(configuration
						.getResponseRemoteFieldName("requested_on"),
						ObjectId.class);

			} catch (PathNotFoundException e) {
				log.info("Unable to deserialize field: " + e.getMessage());
			}

			try {

				object.fromAmount = parser
						.parse(configuration
								.getResponseRemoteFieldName("from_amount"),
								Float.class);

			} catch (PathNotFoundException e) {
				log.info("Unable to deserialize field: " + e.getMessage());
			}

			try {

				object.fromCurrency = parser.parse(configuration
						.getResponseRemoteFieldName("from_currency"),
						String.class);

			} catch (PathNotFoundException e) {
				log.info("Unable to deserialize field: " + e.getMessage());
			}

			try {

				object.rateExpiry = parser
						.parse(configuration
								.getResponseRemoteFieldName("rate_expiry"),
								String.class);

			} catch (PathNotFoundException e) {
				log.info("Unable to deserialize field: " + e.getMessage());
			}

			try {

				object.rateReference = parser.parse(configuration
						.getResponseRemoteFieldName("rate_reference"),
						String.class);

			} catch (PathNotFoundException e) {
				log.info("Unable to deserialize field: " + e.getMessage());
			}

			try {

				object.requestedBy = parser.parse(configuration
						.getResponseRemoteFieldName("requested_by"),
						String.class);

			} catch (PathNotFoundException e) {
				log.info("Unable to deserialize field: " + e.getMessage());
			}

			try {

				object.toAmount = parser.parse(
						configuration.getResponseRemoteFieldName("to_amount"),
						Float.class);

			} catch (PathNotFoundException e) {
				log.info("Unable to deserialize field: " + e.getMessage());
			}

			try {

				object.toCurrency = parser
						.parse(configuration
								.getResponseRemoteFieldName("to_currency"),
								String.class);

			} catch (PathNotFoundException e) {
				log.info("Unable to deserialize field: " + e.getMessage());
			}

			try {

				object.valueDate = parser.parse(
						configuration.getResponseRemoteFieldName("value_date"),
						String.class);

			} catch (PathNotFoundException e) {
				log.info("Unable to deserialize field: " + e.getMessage());
			}

		} else {
			// Default to use gson deserializer
			String json = "";
			if (parser instanceof JsonParser) {
				json = ((JsonParser) parser).getRootElement().toString();
			}

			object = (CorporatePaymentsCrossBorderFxQuote) Utilities
					.transformJsonToObject(json, this.getClass());
		}

		return object;
	}

}
